# Simulation
MODEL_NAME = "testtest"

SECONDS_PER_EPISODE = 50
EPISODES = 250

RENDERING = True
OTHER_TRAFFIC = True
SHIELD = False
CAR_FOLLOWING = True

DESTINATION_DISTANCE = 200
AMOUNT_OF_VEHICLES = 80

REWARD_FUNCTION = 'simple' # simple, complex
SIMPLE_REWARD_A = 3
SIMPLE_REWARD_B = 200
DEST = True

# State and action
WIDTH = 40
HEIGHT = 160
PIXELS_PER_METER = 2

STATE_NUMBER_OF_VEHICLES = 7

FPS = 4
ACTION_TO_STATE_TIME = 0.1

#STEER_ACTIONS = [-1,-0.5,0,0.5,1]
STEER_ACTIONS = [0]
ACC_ACTIONS = [-1,-0.5,0,0.5,1]
STEER_PROBABILITIES = [1]#[0.1, 0.2, 0.4, 0.2, 0.1]
ACC_PROBABILITIES = [0.05, 0.1, 0.15, 0.4, 0.4]

# Shield
BUFFER_TIME = 0.5
BUFFER_DISTANCE = 10

# Q-learning
REPLAY_MEMORY_SIZE = 50_000
MIN_REPLAY_MEMORY_SIZE = 200
MINIBATCH_SIZE = 16
PREDICTION_BATCH_SIZE = 1
TRAINING_BATCH_SIZE = MINIBATCH_SIZE // 4
UPDATE_TARGET_EVERY = 10

LEARNING_RATE = 0.00025

DISCOUNT = 0.99

MIN_EPSILON = 0.01
EPSILON_DECAY = MIN_EPSILON**(1/EPISODES)
SPEED_LIMIT_EXPLORATION = 0.7
EPSILON_DECAY_LINEAR = True

ETA = 0.9

# Other
MEMORY_FRACTION = 0.8
AGGREGATE_STATS_EVERY = 5
