# In this file, all parameters that are used in the rest of the code can be set.

# Simulation
ENVIRONMENT = 2
SECONDS_PER_EPISODE = 30
EPISODES = 1000

RENDERING = True
SHIELD = False
SIP_SHIELD = False

FABRICATE_ACTIONS = False
ALT_LOSS = False

INITIAL_SPEED = 7
AMOUNT_OF_VEHICLES = 100

SIMPLE_REWARD_A = 1
SIMPLE_REWARD_B = 1
SIMPLE_REWARD_C = 1

ACTION_TO_STATE_TIME = 1.5

# Shield
BUFFER_TIME = 2
BUFFER_DISTANCE = 10

# Q-learning
REPLAY_MEMORY_SIZE = 50_000
MIN_REPLAY_MEMORY_SIZE = 200
MINIBATCH_SIZE = 16
PREDICTION_BATCH_SIZE = 1
TRAINING_BATCH_SIZE = MINIBATCH_SIZE // 4
UPDATE_TARGET_EVERY = 10
LEARNING_RATE = 0.00025
DISCOUNT = 0.95
EXPLORATION_STOP = 0.65

# Alternative loss function
LAMBDA = 5

# Behavior evaluation
TEST_SCENARIO = 0

# Other
AGGREGATE_STATS_EVERY = int(EPISODES/10)
PORT = 2000

extra_name = "alt_loss_no_beta"
MODEL_NAME = "Scenario" + str(ENVIRONMENT) + "_Shield" + str(int(SHIELD)) + "_SIPshield" + str(int(SIP_SHIELD)) + "-" + extra_name
